### ISSUE TITLE
Run failed on recent blog post (dunia_yetu), please help

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#323]
<img width="1329" alt="Screenshot 2024-01-26 at 16 05 03" src="https://github.com/threefoldfoundation/www_threefold_io/assets/50134479/b400c6d7-8fb9-4604-8dc6-ad8facd47f72">

**Comment by PeterNashaat** [comment]
- Should be fixed. 
<img width="883" alt="image" src="https://github.com/threefoldfoundation/www_threefold_io/assets/13523434/f3bbc1a7-95fe-423a-a3ba-806e593758cd">

**Comment by samtaggart** [comment]
Thank you! But I am still not seeing the blog on the website. @ehab-hassan @samaradel did I do something wrong?

**Comment by samaradel** [comment]
> Thank you! But I am still not seeing the blog on the website. @ehab-hassan @samaradel did I do something wrong?

![image](https://github.com/threefoldfoundation/www_threefold_io/assets/11662805/97c03414-c3db-40fe-9e36-2bdf7e8c9d30)

fixed, Thanks @PeterNashaat
